In [1]:
import numpy as np

t1 = np.arange(20)

t1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [2]:
t1[0] = 100
t1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [3]:
t1[[0,2,4]] = 200
t1

array([200,   1, 200,   3, 200,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [7]:
t1[t1 > 10] = -1
t1

array([-1,  1, -1,  3, -1,  5,  6,  7,  8,  9, 10, -1, -1, -1, -1, -1, -1,
       -1, -1, -1])

In [12]:
t1 = np.arange(20)
b = t1 > 10 * (-1)
b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [17]:
(t1 > 10) * (-1)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1,
       -1, -1, -1])

# Zbiór mandelbrota: 
